### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by midudev**
Adding hubii.com as website using i18next.

http://hubii.com/?lng=en
http://hubii.com/?lng=es

### CODE REVIEW

**Comment by jamuhl** [comment]
would you mind copying the logo image over to `/img/projects/`?

will be added when done.

**Comment by midudev** [comment]
Done! Thanks @jamuhl for your amazing work, congrats for the library. :)

**Comment by midudev** [comment]
Btw, if it's fine mentioning it or it helps on the popularity of the library. hubii.com has more than 2.5 millions pageviews per month and is in the top 12k of websites worldiwde according to Alexa: http://www.alexa.com/siteinfo/hubii.com

**Comment by jamuhl** [comment]
published http://i18next.com/

thanks for adding hubii.com into the mix

**Pull request merged**
